# Generated by Django 2.0.4 on 2018-05-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0002_auto_20180409_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=256)),
                ('scope', models.CharField(default='', max_length=256)),
                ('last_updated', models.DateTimeField(default='2018-05-09 21:42:20+00:00')),
                ('last_submitted', models.DateTimeField(default='2018-05-09 21:42:20+00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
