# Generated by Django 2.0.4 on 2018-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcemember',
            name='id',
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='access_token',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='moves_id',
            field=models.CharField(default='', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='refresh_token',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='token_expires',
            field=models.DateTimeField(default='2018-04-13 18:21:46+00:00'),
        ),
    ]
