# Generated by Django 2.0.4 on 2018-04-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180413_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemember',
            name='moves_id',
            field=models.CharField(default='', max_length=65, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='token_expires',
            field=models.DateTimeField(default='2018-04-25 23:07:42+00:00'),
        ),
    ]
