# Generated by Django 2.0.4 on 2018-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180425_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-04-19 17:41:41+00:00'),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-04-19 17:41:41+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='token_expires',
            field=models.DateTimeField(default='2018-04-26 17:41:41+00:00'),
        ),
    ]
